# Generated by Django 6.0 on 2025-12-16 21:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SendingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SendingUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('file', models.FileField(upload_to='sending_files/')),
                ('received', models.BooleanField(default=False)),
                ('sending_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('sending_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_units', to='core.sendinggroup')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('access_code', models.CharField(blank=True, max_length=6)),
                ('used', models.BooleanField(default=False)),
                ('sending_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.sendingunit')),
            ],
        ),
    ]
