# Generated by Django 6.0 on 2025-12-17 15:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
