# Generated by Django 6.0 on 2025-12-17 23:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_link_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
